name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  json-data-file-path:
    description: 'Path to json file that represents the data to index'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'node16'
  main: 'index.js'