# This is a basic workflow to help you get started with Actions

name: BuildDocs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    # First get all the repositories we will use to build any of the sites
    steps:
      - run: python -V
      - run: pip install marko

      # This repo
      - name: Checkout docsproto
        uses: actions/checkout@v3
        with:
          path: main

      # This repo's  wiki
      - name: Checkout docsproto wiki 
        uses: actions/checkout@v3
        with:
          repository: ericzinda/docsproto.wiki
          path: docsprotowiki

      # Official docs wiki
      - name: Checkout docs wiki repo
        uses: actions/checkout@v3
        with:
          repository: delph-in/docs.wiki
          path: docswiki
      
      # Remove all pages from "latest" so we don't carry over removed pages
      - run: rm -r -f $GITHUB_WORKSPACE/main/latestsrc/
      - run: mkdir $GITHUB_WORKSPACE/main/latestsrc/
      - run: rm -r -f $GITHUB_WORKSPACE/main/latestsites/
      - run: mkdir $GITHUB_WORKSPACE/main/latestsites/

      # Create blank "conceptual" site
      - run: cp -R $GITHUB_WORKSPACE/main/initial_concept/ $GITHUB_WORKSPACE/main/latestsrc/concept/
      - run: cp -r $GITHUB_WORKSPACE/main/shared_site_layouts $GITHUB_WORKSPACE/main/latestsrc/concept/_layouts

      # Create blank "tools" site
      - run: cp -R $GITHUB_WORKSPACE/main/initial_tools/ $GITHUB_WORKSPACE/main/latestsrc/tools/
      - run: cp -r $GITHUB_WORKSPACE/main/shared_site_layouts $GITHUB_WORKSPACE/main/latestsrc/tools/_layouts

      # Process and copy all pages into the sites
      - run: python $GITHUB_WORKSPACE/main/createdocs.py https://https://blog.inductorsoftware.com/docsproto/ $GITHUB_WORKSPACE/ $GITHUB_WORKSPACE/main/latestsrc/ $GITHUB_WORKSPACE/main/sitesdefinitions.json

#
#      # Gather pages for "conceptual" site
#      ## Set up the blank site
#      - run: cp -R $GITHUB_WORKSPACE/main/initial_concept/ $GITHUB_WORKSPACE/main/latestsrc/concept/
#      - run: cp -r $GITHUB_WORKSPACE/main/shared_site_layouts $GITHUB_WORKSPACE/main/latestsrc/concept/_layouts

#      ## add the pages in
#      - run: cp $GITHUB_WORKSPACE/docswiki/ErgSemantics.md $GITHUB_WORKSPACE/main/latestsrc/concept/
#      - run: cp $GITHUB_WORKSPACE/docswiki/ErgSemantics_Essence.md $GITHUB_WORKSPACE/main/latestsrc/concept/
#      - run: cp $GITHUB_WORKSPACE/docswiki/ErgSemantics_Basics.md $GITHUB_WORKSPACE/main/latestsrc/concept/
#
#      # Gather pages for "tools" site
#      ## Set up the blank site
#      - run: cp -R $GITHUB_WORKSPACE/main/initial_tools/ $GITHUB_WORKSPACE/main/latestsrc/tools/
#      - run: cp -r $GITHUB_WORKSPACE/main/shared_site_layouts $GITHUB_WORKSPACE/main/latestsrc/tools/_layouts
#
#      ## add the pages in
#      - run: cp $GITHUB_WORKSPACE/docswiki/LogonTop.md $GITHUB_WORKSPACE/main/latestsrc/tools/
#      - run: cp $GITHUB_WORKSPACE/docswiki/ToolsTop.md $GITHUB_WORKSPACE/main/latestsrc/tools/

      # Create an index of all the pages
      # - uses: DaanV2/Markdown-Action-Create-Indexes@v1.7.0
      #  with: 
      #    folder: ${{github.workspace}}/main/latestsrc/concept
          
      # Build the site with Jekyll
      - name: Setup Pages
        uses: actions/configure-pages@v1
        
      - name: Build Conceptual with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./main/latestsrc/concept
          destination: main/latestsites/concept
                    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: main/latestsites/

      - name: Build Tools with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./main/latestsrc/tools
          destination: main/latestsites/tools
                    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: main/latestsites/

      # Now commit and push all the changes to record this version of the docs
      - name: Commit files
        run: |
          cd $GITHUB_WORKSPACE/main
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[BOT] Automatic documentation build" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: main
          
  # Deploy the pages to github pages
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
