# This is a basic workflow to help you get started with Actions

name: CopyFiles

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_owner: delph-in
          src_repo_name: docs.wiki
          src_branch: master
          src_path: /AbbeyApposition.md
          dst_owner: EricZinda
          dst_repo_name: docsproto
          dst_branch: master
          dst_path: /wiki/
